parameters:
  team: ''
  stage: ''
  artifact: ''
  appName: ''

stages:
- stage: Deploy_to_${{ parameters.stage }}
  displayName: 'Deploy Artifacts'
  jobs:
  - deployment: Deploy_to_${{ parameters.stage }}
    condition: succeeded()
    environment: ${{ parameters.team }}-${{ parameters.stage }}
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            inputs:
              artifact: ${{ parameters.artifact }}
              targetPath: $(Pipeline.Workspace)
          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: ${{ parameters.stage }}_${{ parameters.team }}
              appType: functionAppLinux
              appName: ${{ parameters.appName }}
              package: "$(Pipeline.Workspace)/${{ parameters.artifact }}/functions.zip"
