## This example is for my presentation site and deploys the same repo
## to two different folders within the same repo. One is used for testing,
## the other is the real site. I chose this because it is already a public 
## example and repo you can go to see it in action. Ideally you would deploy 
## the built content to a different repo though..

name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)
trigger:
  batch: true
  branches:
    include:
    - master

# Don't trigger on PRs
pr: none

resources:
  repositories:
  - repository: pipelines
    type: github
    endpoint: github_services
    name: zloeber/azure-pipeline-library

stages:
## Build Hugo site (DEV)
- template: build/hugo-generate.yml@pipelines
  parameters:
    initialize: true
    baseurl: 'https://zacharyloeber-decks-dev.onrender.com/'
    testhtml: 'false'
    outputpath: './testsite'
    contentpath: './content'
    drafts: 'true'
    target: 'dev'
    artifact: 'devartifact'
- template: deploy/git-folder.yml@pipelines
  parameters:
    repo: 'https://github.com/zloeber/deck.loeber.live.git'
    branch: 'master'
    path: 'testsite'
    environment: 'dev'
    target: 'dev'
    artifact: 'devartifact'

## Build Hugo site (PROD)
- template: build/hugo-generate.yml@pipelines
  parameters:
    initialize: true
    baseurl: 'https://deck.loeber.live/'
    testhtml: 'false'
    outputpath: './public'
    contentpath: './content'
    target: 'prod'
    artifact: 'prodartifact'
- template: deploy/git-folder.yml@pipelines
  parameters:
    repo: 'https://github.com/zloeber/deck.loeber.live.git'
    branch: 'master'
    path: 'public'
    environment: 'production'
    target: 'prod'
    artifact: 'prodartifact'
